### ISSUE TITLE
failed to load module/driver

### ISSUE THREAD

**Issue by feri777** [flathub/org.openshot.OpenShot#1]
Hello, I have problem with run openshot version from flathub.

terminal: 

> $ flatpak run org.openshot.OpenShot

> Loaded modules from installed directory: /app/lib/python3.5/site-packages/openshot_qt
>       launch:INFO ------------------------------------------------
>       launch:INFO    OpenShot (version 2.4.1)
>       launch:INFO ------------------------------------------------
> 
> (python3:2): Gtk-WARNING **: Theme parsing error: gtk.css:5978:26: 'titlebar_fg_color' is not a valid color name
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Unrecognized OpenGL version
> Unrecognized OpenGL version
>

**Comment by feri777** [comment]
Yes I have nvidia card. In system I have installed nvidia-driver-396 (open surce).

> $ flatpak install flathub org.freedesktop.Platform.GL.nvidia-*
> error: Invalid id org.freedesktop.Platform.GL.nvidia-*: Name can't contain *

**Comment by eszlari** [comment]
396.18? This is a beta driver that is not available on flathub.

Use tab completion to see what versions are available:

```
$ flatpak install flathub org.freedesktop.Platform.GL.nvidia-[Tab]
```

**Comment by feri777** [comment]
Ok, I install latest driver from flathub 390-48. I tun openshot but give me same error.

> $ flatpak install flathub org.freedesktop.Platform.GL.nvidia-390-48
> $ flatpak run org.openshot.OpenShot

**Comment by eszlari** [comment]
Your host driver and the flatpak driver must have the same version.

**Comment by feri777** [comment]
I installed nvidia driver 390-48 and now its running. Thank you.
