### ISSUE TITLE
Is anyone using this? Does it work for you?

### ISSUE THREAD

**Issue by ispanos** [flathub/org.openshot.OpenShot#14]
I'm on Pop!_Os and I installed the flatpak version before the deb package in the repo.
I felt like it was in alpha. It crashed a lot, playback wasn't smooth and all in all it was a terible experience.

I installed the native package and 99% of the problems I had where resolved. I'm  only here to ask if you've tried to use this flatpak on Ubuntu/ Pop!_Os or other distros and confirmed that it works properly. I don't think it an issue with my set-up, but it could be.

**Comment by eszlari** [comment]
> It crashed a lot

Please provide the steps to reproduce the crash.

**Comment by ispanos** [comment]
If it was a specific behaviour or frooze the same way every time, I would do that too.
Please take in mind that I'm currenly using a Radeon HD 6950, so that might be causing me the trouble. (Even though the native package worked for me)

I think the first crash was while scrubing on the timeline. I only had 1 clip on and a background picture. When I say crash, the program was not responding for 1-2 minutes and I killed it using Gnome's pop-up ( the one that asks you to to wait or kill the program).

After that everything went downhill. The video wasnt playing back properly, but I fixed it by changing the FPS in "Preferences -> Preview", then it crashed again while playing back the video.. All in all I had made 1 cut in the beggining to mute the first 3 seconds, one `fade` from black on the 3 second clip, an audio fade in the second clip and a fade to black at the end. But there were artifacts during the video fading.

I was genuinly curious if it was an issue with my system and if anyone has tested it on Ubuntu / Pop!_Os.

**Comment by eszlari** [comment]
Provide the output if you start the app from the command line:
```
$ flatpak run org.openshot.OpenShot
```

Provide the output of:
```
$ journalctl -f
```

when the app crashes/misbehaves.

> I'm currenly using a Radeon HD 6950

Flatpak uses newer versions of Mesa, so this could be a regression in the driver.

**Comment by eszlari** [comment]
Do other editors (shotcut, kdenlive, olive, flowblade, pitivi) work better?

**Comment by Mershl** [comment]
Give it a try with the latest version (pushed yesterday by @hfiguiere, thank you mate!). Performance has improved tremendously for me - especially for the live preview.
