### ISSUE TITLE
libvorbis missing from Flatpak build

### ISSUE THREAD

**Issue by ferdnyc** [flathub/org.openshot.OpenShot#19]
Hi, over at OpenShot/openshot-qt#4462 @potatoleek reported a crash with the Flatpak build of OpenShot, due to a missing audio codec when trying to export WEBM (vpx).

The audio codec defined there is libvorbis — can you please confirm whether vorbis is enabled in the Flatpak ffmpeg build?

**Comment by ferdnyc** [comment]
Actually, after running `flatpak run org.openshot.OpenShot` and then doing a `flatpak enter $INSTANCE bash`, I can report with certainty that there's no `libvorbis.so*` in the container's `/app/lib/`, and `/app/lib/libavcodec.so` is not linked with any Ogg codecs.

**Comment by hfiguiere** [comment]
libvorbis is in the runtime.

```
$ ls -l /usr/lib/x86_64-linux-gnu/libvorbis*
lrwxrwxrwx 1 nfsnobody nfsnobody     22 Sep 29 13:52 /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 -> libvorbisenc.so.2.0.12
-rwxr-xr-x 8 nfsnobody nfsnobody 707400 Sep 16 00:20 /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.12
lrwxrwxrwx 1 nfsnobody nfsnobody     22 Sep 29 13:52 /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 -> libvorbisfile.so.3.3.8
-rwxr-xr-x 8 nfsnobody nfsnobody  40784 Sep 16 00:20 /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.8
lrwxrwxrwx 1 nfsnobody nfsnobody     18 Sep 29 13:52 /usr/lib/x86_64-linux-gnu/libvorbis.so.0 -> libvorbis.so.0.4.9
-rwxr-xr-x 8 nfsnobody nfsnobody 189896 Sep 16 00:20 /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.9
```

**Comment by ferdnyc** [comment]
Mmm, and it's linked into `/usr/lib/x86_64-linux-gnu/libavcodec.so.58` as well. But it looks like the OpenShot build has its own `/app/lib/libavcodec.so.58` it's using instead?

**Comment by ferdnyc** [comment]
Yup.

```sh
bash-5.1$ ldd /app/lib/python3.8/site-packages/_openshot.so |grep app
	libopenshot.so.21 => /app/lib/libopenshot.so.21 (0x00007fc3063e9000)
	libopenshot-audio.so.8 => /app/lib/libopenshot-audio.so.8 (0x00007fc3061ac000)
	libavcodec.so.58 => /app/lib/libavcodec.so.58 (0x00007fc30336f000)
	libavformat.so.58 => /app/lib/libavformat.so.58 (0x00007fc30311d000)
	libavutil.so.56 => /app/lib/libavutil.so.56 (0x00007fc303008000)
	libswscale.so.5 => /app/lib/libswscale.so.5 (0x00007fc302f7b000)
	libswresample.so.3 => /app/lib/libswresample.so.3 (0x00007fc302f5c000)
	libzmq.so.5 => /app/lib/libzmq.so.5 (0x00007fc302e5e000)
	libresvg.so => /app/lib/libresvg.so (0x00007fc302cbc000)
	libMagick++-7.Q16HDRI.so.4 => /app/lib/libMagick++-7.Q16HDRI.so.4 (0x00007fc302c0a000)
	libMagickCore-7.Q16HDRI.so.7 => /app/lib/libMagickCore-7.Q16HDRI.so.7 (0x00007fc302769000)
	libx264.so.160 => /app/lib/libx264.so.160 (0x00007fc2ffdc3000)
	libMagickWand-7.Q16HDRI.so.7 => /app/lib/libMagickWand-7.Q16HDRI.so.7 (0x00007fc2ffae8000)
```

**Comment by ferdnyc** [comment]
PR #21 does fix this specific issue, so that's appreciated. Many thanks, @hfiguiere.

For the record, though — in terms of the larger packaging structure, OpenShot has no specific requirements regarding exact FFmpeg builds. We don't apply any custom patches or insist on any particular configuration. So, there seems to be little to justify a separate, application-specific build of the FFmpeg libraries, if they're already part of the shared runtime. I'm struggling to understand why specifically those exist at all.

Looking at how the current `/app/lib/libav*.so` libraries are built, I don't immediately see any reason why OpenShot couldn't just be using the runtime's FFmpeg directly.

It seems like a lot of wasted effort, maintaining a custom build and having to contend with issues like these. Is there some reason that `/app/lib/libav*` FFmpeg build needs to be part of the OpenShot Flatpak?

**Comment by hfiguiere** [comment]
Runtime builds are missing important codecs (uncumbered) it seems.

I didn't do the original package though.

**Comment by ferdnyc** [comment]
@hfiguiere Ahh, that makes sense, I didn't think about the fact that Flatpak runtime probably meets Fedora packaging standards; OpenShot is packaged in RPMFusion there (as is ffmpeg itself).
