### ISSUE TITLE
Add resvg

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [flathub/org.openshot.OpenShot#3]
OpenShot now supports: resvg. If resvg is present on the build environment, libopenshot will compile to use resvg.

Here is a script that we currently use to manually install resvg: https://gist.github.com/peanutbutterandcrackers/73d3af8040b82b1d3e64930c6562d4c6

Please add resvg to OpenShot for the next release. Thank you!

**Comment by eszlari** [comment]
done: https://github.com/flathub/org.openshot.OpenShot/commit/ec2077f6edee6783db2cef783b7939ad0e1a9b4b
