### ISSUE TITLE
Flathub description contains HTML tags

### ISSUE THREAD

**Issue by marcosps** [flathub/org.openshot.OpenShot#31]
See https://flathub.org/apps/org.openshot.OpenShot:

<em>Features include:</em>

    <em>Free & open-source</em> (licensed under GPLv3)
    <em>Cross-platform</em> (Linux, OS X, Chrome OS, and Windows)

It doesn't affect the product in any means, but maybe nobody noticed this before.

**Comment by hfiguiere** [comment]
this comes from upstream provided appstream file.

**Comment by hfiguiere** [comment]
Actually it's https://github.com/flathub/website/issues/131

**Comment by hfiguiere** [comment]
And it was fixed in the backend.
