### ISSUE TITLE
Flathub build 3.1.1 is missing a lot of effects

### ISSUE THREAD

**Issue by JPT77** [flathub/org.openshot.OpenShot#34]
**Describe the bug:**
Several effects are missing from the flatpak build, one of these is stabilizer. For the others see pics below.

**Steps to reproduce the behavior:**
Open effects tab, see list of video effects

**Expected behavior:**
stabilizer available

**System Details:**
Flatpak: OpenShot Studios, LLC org.openshot.OpenShot 3.1.1 stable system
Kubuntu 23.10, kernel 6.5.0-28-generic

Available video effects in Appimage build
![openshot-appimage](https://github.com/flathub/org.openshot.OpenShot/assets/4168125/6969ddf9-66d7-43c6-af1a-9a4c06432d7f)
Available video effects in Flatpak build
![openshot-flatpak](https://github.com/flathub/org.openshot.OpenShot/assets/4168125/201d69e2-d3ac-462c-aa9e-5f61d137a8c0)

So is this the right place to report problems with flatpak builds of software?
thank you very much

see also my bug report on openshot: https://github.com/OpenShot/openshot-qt/issues/5504

**Comment by hfiguiere** [comment]
where does that effect come from?

**Comment by JPT77** [comment]
I am sorry, I do not know. I am just a user. No idea about the source code. 

The follwoing effects are missing:
- stabilizer
- object detector
- "Verfolger", maybe tracer in english?
all of these seem to analyze the picture content, so there may be a library missing.

**Comment by hfiguiere** [comment]
3 is not "a lot". it's "a few"
